version: '3'
services:
  react:
    build:
      context: .
      dockerfile: ./docker/reactfrontend/Dockerfile
    container_name: reactfrontend_container
    tty: true
    volumes:
      - ./reactfrontend:/app/react
    command: sh -c "cd /app/react && npm install && npm run dev --host"
    ports:
      - 3000:3000
  go:
    build:
      context: .
      dockerfile: ./docker/gobackend/Dockerfile
    container_name: gobackend_container
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./gobackend:/app/go
    command: sh -c "cd /app/go && go build -o main . && /app/go/main"
